# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

export homedir = "/home"

BBFILE_COLLECTIONS += "meta-sidos"
BBFILE_PATTERN_meta-sidos = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-sidos = "6"

LAYERDEPENDS_meta-sidos = "core"
LAYERSERIES_COMPAT_meta-sidos = "styhead"
